#!/usr/bin/env bash
# Sync Stripe keys from CLI into .env (local) and .env.fly (production secrets template).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if ! command -v stripe >/dev/null 2>&1; then
  echo "Install Stripe CLI: brew install stripe/stripe-cli/stripe"
  exit 1
fi

TEST_SK=$(stripe config --list 2>/dev/null | grep "test_mode_api_key" | sed "s/.*= '//;s/'$//")
LIVE_RK=$(stripe config --list 2>/dev/null | grep "live_mode_api_key" | sed "s/.*= '//;s/'$//" || true)
LOCAL_WHSEC=$(stripe listen --print-secret -e checkout.session.completed 2>/dev/null | tail -1)
PROD_TEST_WHSEC="whsec_Q48Jmolv7yxtagmad9i924DgsXhntzCM"

# Local .env
if [[ -f .env ]]; then
  perl -i -pe "s/^STRIPE_SECRET_KEY=.*/STRIPE_SECRET_KEY=${TEST_SK}/" .env
  perl -i -pe "s/^STRIPE_WEBHOOK_SECRET=.*/STRIPE_WEBHOOK_SECRET=${LOCAL_WHSEC}/" .env
else
  cp .env.example .env
  perl -i -pe "s/^STRIPE_SECRET_KEY=.*/STRIPE_SECRET_KEY=${TEST_SK}/" .env
  perl -i -pe "s/^STRIPE_WEBHOOK_SECRET=.*/STRIPE_WEBHOOK_SECRET=${LOCAL_WHSEC}/" .env
  perl -i -pe "s/^# AIBC_DEV_BYPASS=.*/AIBC_DEV_BYPASS=1/" .env || echo "AIBC_DEV_BYPASS=1" >> .env
fi

# Fly / production template (gitignored)
cat > .env.fly << EOF
# Paste into: fly secrets set \$(grep -v '^#' .env.fly | xargs)
# Generated by: npm run stripe:sync

AIBC_PUBLIC_URL=https://api.aibcmedia.com
AIBC_PORTAL_URL=https://aibcmedia.com
AIBC_CORS_ORIGINS=https://aibcmedia.com,https://www.aibcmedia.com

# Test mode until live secret key is available in CLI
STRIPE_SECRET_KEY=${TEST_SK}
STRIPE_WEBHOOK_SECRET=${PROD_TEST_WHSEC}

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
EOF

echo "[stripe] Local .env updated (test key + listen webhook secret)"
echo "[stripe] Production template → .env.fly"
echo "[stripe] Account: AIBC (acct_1ScW4SJelDe3AJZ5)"
if [[ -n "$LIVE_RK" && "$LIVE_RK" == rk_live_* ]]; then
  echo "[stripe] Note: CLI live key is restricted — create LIVE webhook in Stripe Dashboard when ready."
fi
